const mongoose=require("mongoose");

const PgSchema=mongoose.Schema({
    name:{
        type:String,
    },
    select:{
        type:String
    },
    gender:{
        type:String
    },
    file:{
        type:String
    },
    price:{
        type:Number
    },
    number:{
        type:Number
    },
    deposite:{
        type:String
    },
    nearcollege:{
        type:String
    },
    numberbed:{
        type:String
    },
    address:{
        type:String
    },
    wifi:{
        type:Boolean
    },
    powerbackup:{
        type:Boolean
    },
    studyroom:{
        type:Boolean
    },
    roomcleaning:{
        type:Boolean
    },
    parking:{
        type:Boolean
    },
    ac:{
        type:Boolean
    },
    kitchen:{
        type:Boolean
    },
    noticeperiod:{
        type:Boolean
    },
    foodcharges:{
        type:Boolean
    },
    smoking:{
        type:Boolean
    },
    foodavailable:{
        type:Boolean
    },
    visitorentry:{
        type:Boolean
    },
    visitorallowed:{
        type:Boolean
    },
    meals:{
        type:Boolean
    },
    kitchen:{
        type:Boolean
    },
    freeparking:{
        type:Boolean
    },
    reception:{
        type:Boolean
    },
    lift:{
        type:Boolean
    },
    loudmusic:{
        type:Boolean
    },
    drinking:{
        type:Boolean
    },
    party:{
        type:Boolean
    },
    oppositegender:{
        type:Boolean
    },
    getclosingtime:{
        type:Boolean
    },
    carparking:{
        type:Boolean
    },
    nonvegfood:{
        type:Boolean
    },
    token:{
        type:String
    }

})
const Pgs=new mongoose.model("Pg",PgSchema)
module.exports =Pgs